name: Add Commit Details to ClickUp

on:
  push:
    branches:
      - '**'

jobs:
  clickup-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Parse Commit Messages
        id: parse_commit
        run: |
          echo "Parsing commits for ClickUp links"
          commits=$(git log -1 --pretty=format:"%s")
          echo "Latest Commit: $commits"
          if [[ "$commits" =~ https://app.clickup.com/t/([a-zA-Z0-9]+) ]]; then
            task_id="${BASH_REMATCH[1]}"
            echo "Found Task ID: $task_id"
            # Export task_id to be used in subsequent steps
            echo "task_id=$task_id" >> $GITHUB_ENV
          else
            echo "Task ID not found in the commit message."
          fi

      - name: Post to ClickUp
        env:
          CLICKUP_API_KEY: ${{ secrets.CLICKUP_API_KEY }}
        run: |
          echo "CLICKUP_API_KEY: $CLICKUP_API_KEY"
          if [ -n "$task_id" ]; then
            echo "Found Task ID: $task_id"
            # curl -X POST "https://api.clickup.com/api/v2/task/$task_id/comment" \
            # -H "Authorization: $CLICKUP_API_KEY" \
            # -H "Content-Type: application/json" \
            # -d '{"comment": "This is an automated comment from the script."}'
          else
            echo "Task ID not found in the commit message."
          fi
